#!/bin/bash

export NOPAUSE=1
args=$0
SCRIPTDIR=$(dirname "${args}")
cd $SCRIPTDIR
SCRIPTDIR=`pwd`

if [ "$BUILDING_release" == "1" ]; then
  releasetype="release"
  GHOWNER=`whoami`
else
  releasetype="nightly"
  GHOWNER=firemodels
fi

#run time libraries are located in
#  $HOME/.bundle/BUNDLE/MPI

if [ "$INTEL_MPI_VERSION" != "" ]; then
  intel_mpi_version=$INTEL_MPI_VERSION
fi
if [ "$MPI_VERSION" != "" ]; then
  mpi_version=$MPI_VERSION
fi
if [ "$OPENMPI_DIR" != "" ]; then
  openmpi_dir=$OPENMPI_DIR
fi

#---------------------------------------------
#                   usage
#---------------------------------------------

function usage {
echo "This script builds a bundle using applications built by firebot, FDS pubs"
echo "built by firebot, Smokeview pubs built by smokebot and other files found"
echo "in the fds, smv and bot repos."
echo ""
echo "Options:"
echo "Parameters specifying branch used to build the bundle"
echo "-b branch_name - use branch named branch_name to make the bundle [default: $BRANCH]"
echo "-r - use a branch named release"
echo "-t - use a branch named test"
echo ""
echo "Other parmeters"
echo "-d dir - directory containing bundle generated by this script"
echo "     [default: $bundle_dir]"
echo "-f - force this script to run"
echo "-h - display this message"
echo "-U - upload bundle file to Github"
echo "-v - show parameters used to build bundle (the bundle is not generated)"
echo "-w - overwrite bundle (if it already exists) "
echo "-X FDS_TAG - fds tag"
echo "-Y SMV_TAG - smv tag"
exit 0
}

showparms=
ECHO=
bundle_dir=$HOME/.bundle/bundles
OVERWRITE=
UPLOADBUNDLE=
FORCE=
CURDIR=`pwd`
OUTPUT_DIR=$CURDIR/output
SYNC_REVS=
BRANCH=master
BUNDLE_PREFIX="nightly"
FDS_REVISION=
SMV_REVISION=
FDS_TAG=
SMV_TAG=
INSTALL=

while getopts 'Bb:d:fhrtvwX:Y:U' OPTION
do
case $OPTION  in
  B)
   INSTALL=1
   ;;
  b)
   BRANCH=$OPTARG
   ;;
  d)
   bundle_dir=$OPTARG
   ;;
  f)
   FORCE="1"
   ;;
  h)
   usage;
   ;;
  r)
   BRANCH=release
   ;;
  t)
   BRANCH=test
   ;;
  U)
   UPLOADBUNDLE=1
   ;;
  v)
   showparms=1
   ECHO=echo
   ;;
  w)
   OVERWRITE=1
   ;;
  X)
   FDS_TAG=$OPTARG
   ;;
  Y)
   SMV_TAG=$OPTARG
   ;;
esac
done
shift $(($OPTIND-1))

if [ "$FDS_TAG" != "" ]; then
  FDS_REVISION=$FDS_TAG
fi
if [ "$SMV_TAG" != "" ]; then
  SMV_REVISION=$SMV_TAG
fi

# prevent more than one instance of this script from running at the same time

LOCK_FILE=$HOME/.bundle/make_bundle_lock
if [ "$FORCE" == "" ]; then
  if [ -e $LOCK_FILE ]; then
    echo "***error: another instance of $0 is running."
    echo "          If this is not the case, re-run after removing"
    echo "          the lock file: $LOCKFILE"
    exit 1
  fi
fi
touch $LOCK_FILE

if [ "$showparms" == "" ]; then
  if [ ! -d $OUTPUT_DIR ]; then
    mkdir $OUTPUT_DIR
  fi
  rm -f $OUTPUT_DIR/*
fi

# determine platform script is running on

if [ "`uname`" == "Darwin" ]; then
  platform=osx
  export FDS_OPENMPIDIR=$openmpi_dir
else
  platform=lnx
fi

if [ "$BRANCH" == "release" ]; then
  BUNDLE_PREFIX=
fi

BUNDLE_PREFIX_FILE=
if [ "$BUNDLE_PREFIX" != "" ]; then
  BUNDLE_PREFIX_FILE=${BUNDLE_PREFIX}_
fi
BRANCHDIR=$BRANCH
if [ "$BRANCH" != "release" ]; then
  BRANCHDIR=
fi
UPLOAD_DIR=
if [ "$BRANCH" == "release" ]; then
  UPLOAD_DIR="bundle_test"
fi

if [ "$showparms" == "1" ]; then
  echo ""
  echo " Parameters"
  echo " ----------"
  echo "              MPI version: $mpi_version"
  echo "            Intel version: $intel_mpi_version"
  if [ "$openmpi_dir" != "" ]; then
    echo "              openmpi dir: $openmpi_dir"
  fi
  echo "    fds/smv app directory: $SCRIPTDIR/apps on this computer"
  echo "         bundle directory: $bundle_dir"
  if [ "$OVERWRITE" == "1" ]; then
    echo "         overwrite bundle: yes"
  else
    echo "         overwrite bundle: no"
  fi
  echo ""
fi

return_code=0
if [[ "$showparms" == "" ]]; then
  error_log=$SCRIPTDIR/output/error_nightly.log
  ./copy_pubs.sh fds $releasetype $SCRIPTDIR/pubs $GHOWNER $error_log || return_code=1
  ./copy_pubs.sh smv $releasetype $SCRIPTDIR/pubs $GHOWNER $error_log || return_code=1

  if [ "$return_code" == "1" ]; then
    cat $error_log
    echo ""
    echo "bundle generation aborted"
    rm -f $LOCK_FILE
    exit 1
  fi
fi

# get fds and smv repo revision used to build apps

FDSREV=$FDS_REVISION
if [ "$FDS_REVISION" == "" ]; then
  if [ -e $SCRIPTDIR/apps/FDS_REVISION ]; then
    FDSREV=`cat $SCRIPTDIR/apps/FDS_REVISION`
  else
    FDSREV=fdstest
  fi
fi

SMVREV=$SMV_REVISION
if [ "$SMV_REVISION" == "" ]; then
  if [ -e $SCRIPTDIR/apps/SMV_REVISION ]; then
    SMVREV=`cat $SCRIPTDIR/apps/SMV_REVISION`
  else
    SMVREV=smvtest
  fi
fi

cd ../../..
REPO_ROOT=`pwd`
cd $CURDIR
installer_base=${FDSREV}_${SMVREV}
installer_base_platform=${installer_base}_${BUNDLE_PREFIX_FILE}$platform
if [[ "$showparms" == "" ]] && [[ "$OVERWRITE" == "" ]]; then
  installer_file=$bundle_dir/${installer_base_platform}.sh
  if [ -e $installer_file ]; then
    echo "***warning: the installer file $installer_file exists."
    echo "             Use the -w option to overwrite it."
    rm -f $LOCK_FILE
    exit 1
  fi
fi

cd $SCRIPTDIR
if [ "$showparms" == "" ]; then
  echo ""
  echo -n "building installer"
  $ECHO ./make_bundle.sh $FDSREV $SMVREV $mpi_version $intel_mpi_version $bundle_dir $BUNDLE_PREFIX > $OUTPUT_DIR/stage1
  make_bundle_status=$?
  
  echo
  echo ***Virus scan summary
  if [ -e $OUTPUT_DIR/scanlog ]; then
    grep -v OK$ $OUTPUT_DIR/scanlog | grep -v ^$ | grep -v SUMMARY
  else
    echo virus scanner not available, bundle was not scanned
  fi

  echo " - complete"
  if [[ "$UPLOADBUNDLE" == "1" ]] && [[ $make_bundle_status -eq 0 ]]; then
    echo ""
    echo "uploading installer"
    
    FILELIST=`gh release view FDS_TEST  -R github.com/$GHOWNER/test_bundles | grep SMV | grep FDS | grep $platform | awk '{print $2}'`
    for file in $FILELIST ; do
      gh release delete-asset FDS_TEST $file -R github.com/$GHOWNER/test_bundles -y
    done

    gh release upload FDS_TEST $bundle_dir/${installer_base_platform}.sh         -R github.com/$GHOWNER/test_bundles  --clobber
    if [ "$platform" == "lnx" ]; then
      cd $REPO_ROOT/fds
      FDS_SHORT_HASH=`git rev-parse --short HEAD`
      cd $SCRIPTDIR
      ./setreleasetitle.sh fds $FDS_SHORT_HASH
    fi
  fi
fi
if [ "$ECHO" == "" ]; then
  LATEST=$bundle_dir/FDS_SMV_latest_$platform.sh
  BUNDLEBASE=$bundle_dir/${installer_base_platform}
  if [ -e ${BUNDLEBASE}.sh ]; then
    rm -f  $LATEST
    ln -s ${BUNDLEBASE}.sh $LATEST
  fi
  cp $REPO_ROOT/bot/Bundlebot/nightly/autoinstall.txt $bundle_dir/.
  rm -f  ${BUNDLEBASE}.tar.gz
  rm -rf $BUNDLEBASE
  if [ "$INSTALL" != "" ]; then
    cd $bundle_dir
    cat autoinstall.txt | bash $LATEST >& $HOME/.bundle/bundle_lnx_nightly_install.log
  fi
fi
rm -f $LOCK_FILE
exit 0
